# Source: https://github.com/pre-commit/pre-commit/blob/main/.pre-commit-config.yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-ast
    -   id: check-yaml
    -   id: check-toml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: detect-private-key
- repo: https://github.com/returntocorp/semgrep
  rev: v1.21.0
  hooks:
    - id: semgrep
      name: semgrep
      entry: semgrep
      args: ["--config=auto", "--disable-version-check", "--skip-unknown-extensions"]
- repo: https://github.com/feluelle/airflint
  rev: v0.3.2-alpha
  hooks:
    - id: airflint
      args: ["-a"]
      additional_dependencies:
        - apache-airflow
        - apache-airflow-providers-cncf-kubernetes
- repo: https://github.com/pycqa/autoflake
  rev: v2.1.1
  hooks:
    - id: autoflake
      args: ["--remove-all-unused-imports", "--in-place"]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.284
  hooks:
    - id: ruff
      args: [ --fix, --exit-non-zero-on-fix ]
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.4.0
    hooks:
    -   id: setup-cfg-fmt
-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.10.0
    hooks:
    -   id: reorder-python-imports
        exclude: ^(pre_commit/resources/|testing/resources/python3_hooks_repo/)
        args: [--py38-plus, --add-import, 'from __future__ import annotations']
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v3.0.1
    hooks:
    -   id: add-trailing-comma
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    - id: black
